#Prints '- NBTTooltip -' before the NBT tag.
#This tag doesn't scroll with the text.
"Show separator" = true
#The text won't have indentation and will.
#all align to the left margin.
"Compress text horizontally" = false
#Determines when the tooltip should be shown. The key used for
#key-based triggers is configurable through the controls menu.
#Allowed Values: F3H, ALWAYS_ON, TOGGLE_ON_KEY, SHOW_ON_KEY
"Trigger Type" = "ALWAYS_ON"
#Prints '- NBT start -' and '- NBT end -'.
#inside the tag, scrolling with the rest.
"Show delimiters" = true
#Allows to show just the NBT part of a tooltip
#when holding CTRL down, hiding the rest.
"Just NBT with CTRL" = true
#Divides long lines into multiple ones and
#places a sing at the beginning of each part.
"Split long lines" = true
#The maximum amount of lines shown in a
#tooltip before it starts scrolling.
"Maximum NBT lines" = 10
#The amount of ticks after which a new line
#is shown when the tooltip is too long.
"Scroll delay" = 20
#FRIENDLY uses a human-readable format for tooltips
#JSON uses the standard JSON format for files.
#Allowed Values: FRIENDLY, FRIENDLY_NO_COLOR, JSON
"Tooltip presentation" = "FRIENDLY"
#FRIENDLY uses a human-readable format to copy nbt
#JSON uses the standard JSON format for files.
#Allowed Values: FRIENDLY, MC_GIVE_CMD, JSON
"Copy format" = "JSON"

